#Server
server:
  servlet:
    context-path: /api

# Database
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lesson27_jdbc
    username: root
    password: 9366
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  jackson:
    default-property-inclusion:
      - non_null
      - non_empty
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

# Logging
logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug
